-- =============================================================================
-- Auto-generated PostgreSQL schema from CSV files
-- Source: /Users/francischungcheengam/Documents/opencode-example/assets/csv
-- Generated by: scripts/generate_schema.py
-- =============================================================================

-- ── abilities.csv ──
CREATE TABLE IF NOT EXISTS abilities (
    id BIGINT PRIMARY KEY,
    name TEXT,
    flavor_text TEXT
);

-- UPSERT template for abilities:
-- INSERT INTO abilities (id, name, flavor_text) VALUES (%(id)s, %(name)s, %(flavor_text)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, flavor_text = EXCLUDED.flavor_text;

-- ── aliases.csv ──
CREATE TABLE IF NOT EXISTS aliases (
    alias TEXT,
    pokemon_id BIGINT
);

-- UPSERT template for aliases:
-- INSERT INTO aliases (alias, pokemon_id) VALUES (%(alias)s, %(pokemon_id)s);

-- ── egg-groups.csv ──
CREATE TABLE IF NOT EXISTS egg_groups (
    id BIGINT PRIMARY KEY,
    name TEXT
);

-- UPSERT template for egg_groups:
-- INSERT INTO egg_groups (id, name) VALUES (%(id)s, %(name)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name;

-- ── evolutions-raw.csv ──
CREATE TABLE IF NOT EXISTS evolutions_raw (
    prevo_name TEXT,
    prevo_form TEXT,
    evo_name TEXT,
    evo_form TEXT,
    base_evo_name TEXT,
    base_evo_form TEXT,
    method TEXT
);

-- UPSERT template for evolutions_raw:
-- INSERT INTO evolutions_raw (prevo_name, prevo_form, evo_name, evo_form, base_evo_name, base_evo_form, method) VALUES (%(prevo_name)s, %(prevo_form)s, %(evo_name)s, %(evo_form)s, %(base_evo_name)s, %(base_evo_form)s, %(method)s);

-- ── evolutions.csv ──
CREATE TABLE IF NOT EXISTS evolutions (
    prevo_id BIGINT,
    evo_id BIGINT,
    base_evo_id BIGINT,
    method TEXT
);

-- UPSERT template for evolutions:
-- INSERT INTO evolutions (prevo_id, evo_id, base_evo_id, method) VALUES (%(prevo_id)s, %(evo_id)s, %(base_evo_id)s, %(method)s);

-- ── games.csv ──
CREATE TABLE IF NOT EXISTS games (
    id BIGINT PRIMARY KEY,
    name TEXT
);

-- UPSERT template for games:
-- INSERT INTO games (id, name) VALUES (%(id)s, %(name)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name;

-- ── gender-ratios.csv ──
CREATE TABLE IF NOT EXISTS gender_ratios (
    id BIGINT PRIMARY KEY,
    name TEXT
);

-- UPSERT template for gender_ratios:
-- INSERT INTO gender_ratios (id, name) VALUES (%(id)s, %(name)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name;

-- ── learn-methods.csv ──
CREATE TABLE IF NOT EXISTS learn_methods (
    id BIGINT PRIMARY KEY,
    name TEXT
);

-- UPSERT template for learn_methods:
-- INSERT INTO learn_methods (id, name) VALUES (%(id)s, %(name)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name;

-- ── learnsets-raw.csv ──
CREATE TABLE IF NOT EXISTS learnsets_raw (
    unique_name TEXT,
    game TEXT,
    move_name TEXT,
    learn_method TEXT,
    level BIGINT
);

-- UPSERT template for learnsets_raw:
-- INSERT INTO learnsets_raw (unique_name, game, move_name, learn_method, level) VALUES (%(unique_name)s, %(game)s, %(move_name)s, %(learn_method)s, %(level)s);

-- ── learnsets-suppl.csv ──
CREATE TABLE IF NOT EXISTS learnsets_suppl (
    unique_name TEXT,
    game TEXT,
    move_name TEXT,
    learn_method TEXT,
    level TEXT
);

-- UPSERT template for learnsets_suppl:
-- INSERT INTO learnsets_suppl (unique_name, game, move_name, learn_method, level) VALUES (%(unique_name)s, %(game)s, %(move_name)s, %(learn_method)s, %(level)s);

-- ── learnsets.csv ──
CREATE TABLE IF NOT EXISTS learnsets (
    pokemon_id BOOLEAN,
    move_id BIGINT,
    game_id BOOLEAN,
    learn_method_id BIGINT,
    level BIGINT
);

-- UPSERT template for learnsets:
-- INSERT INTO learnsets (pokemon_id, move_id, game_id, learn_method_id, level) VALUES (%(pokemon_id)s, %(move_id)s, %(game_id)s, %(learn_method_id)s, %(level)s);

-- ── legalities.csv ──
CREATE TABLE IF NOT EXISTS legalities (
    pokemon_id BIGINT,
    bank_beast BOOLEAN,
    bank_dream BOOLEAN,
    bank_apri BOOLEAN,
    bank_safari BOOLEAN,
    bank_sport BOOLEAN,
    home_beast BOOLEAN,
    home_dream BOOLEAN,
    home_apri BOOLEAN,
    home_safari BOOLEAN,
    home_sport BOOLEAN
);

-- UPSERT template for legalities:
-- INSERT INTO legalities (pokemon_id, bank_beast, bank_dream, bank_apri, bank_safari, bank_sport, home_beast, home_dream, home_apri, home_safari, home_sport) VALUES (%(pokemon_id)s, %(bank_beast)s, %(bank_dream)s, %(bank_apri)s, %(bank_safari)s, %(bank_sport)s, %(home_beast)s, %(home_dream)s, %(home_apri)s, %(home_safari)s, %(home_sport)s);

-- ── move-categories.csv ──
CREATE TABLE IF NOT EXISTS move_categories (
    id BIGINT PRIMARY KEY,
    name TEXT
);

-- UPSERT template for move_categories:
-- INSERT INTO move_categories (id, name) VALUES (%(id)s, %(name)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name;

-- ── moves-raw.csv ──
CREATE TABLE IF NOT EXISTS moves_raw (
    name TEXT,
    type TEXT,
    category TEXT,
    flavor_text TEXT,
    base_power BIGINT,
    accuracy BIGINT,
    pp BIGINT
);

-- UPSERT template for moves_raw:
-- INSERT INTO moves_raw (name, type, category, flavor_text, base_power, accuracy, pp) VALUES (%(name)s, %(type)s, %(category)s, %(flavor_text)s, %(base_power)s, %(accuracy)s, %(pp)s);

-- ── moves.csv ──
CREATE TABLE IF NOT EXISTS moves (
    id BIGINT PRIMARY KEY,
    name TEXT,
    type_id BIGINT,
    category_id BIGINT,
    flavor_text TEXT,
    base_power BIGINT,
    accuracy BIGINT,
    pp BIGINT
);

-- UPSERT template for moves:
-- INSERT INTO moves (id, name, type_id, category_id, flavor_text, base_power, accuracy, pp) VALUES (%(id)s, %(name)s, %(type_id)s, %(category_id)s, %(flavor_text)s, %(base_power)s, %(accuracy)s, %(pp)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, type_id = EXCLUDED.type_id, category_id = EXCLUDED.category_id, flavor_text = EXCLUDED.flavor_text, base_power = EXCLUDED.base_power, accuracy = EXCLUDED.accuracy, pp = EXCLUDED.pp;

-- ── natures.csv ──
CREATE TABLE IF NOT EXISTS natures (
    pokemon_id BIGINT,
    penny TEXT,
    jemma_swsh TEXT,
    jemma_bdsp TEXT,
    jemma_g7 TEXT
);

-- UPSERT template for natures:
-- INSERT INTO natures (pokemon_id, penny, jemma_swsh, jemma_bdsp, jemma_g7) VALUES (%(pokemon_id)s, %(penny)s, %(jemma_swsh)s, %(jemma_bdsp)s, %(jemma_g7)s);

-- ── pokemon-raw.csv ──
CREATE TABLE IF NOT EXISTS pokemon_raw (
    name TEXT,
    form TEXT,
    unique_name TEXT,
    ndex BIGINT,
    galar_dex BIGINT,
    ioa_dex BIGINT,
    ct_dex BIGINT,
    paldea_dex BIGINT,
    tm_dex BIGINT,
    id_dex BIGINT,
    type1 TEXT,
    type2 TEXT,
    hp BIGINT,
    atk BIGINT,
    def BIGINT,
    spa BIGINT,
    spd BIGINT,
    spe BIGINT,
    egg_group1 TEXT,
    egg_group2 TEXT,
    gender_ratio TEXT,
    ability1 TEXT,
    ability2 TEXT,
    hidden_ability TEXT,
    egg_cycles BIGINT,
    url TEXT
);

-- UPSERT template for pokemon_raw:
-- INSERT INTO pokemon_raw (name, form, unique_name, ndex, galar_dex, ioa_dex, ct_dex, paldea_dex, tm_dex, id_dex, type1, type2, hp, atk, def, spa, spd, spe, egg_group1, egg_group2, gender_ratio, ability1, ability2, hidden_ability, egg_cycles, url) VALUES (%(name)s, %(form)s, %(unique_name)s, %(ndex)s, %(galar_dex)s, %(ioa_dex)s, %(ct_dex)s, %(paldea_dex)s, %(tm_dex)s, %(id_dex)s, %(type1)s, %(type2)s, %(hp)s, %(atk)s, %(def)s, %(spa)s, %(spd)s, %(spe)s, %(egg_group1)s, %(egg_group2)s, %(gender_ratio)s, %(ability1)s, %(ability2)s, %(hidden_ability)s, %(egg_cycles)s, %(url)s);

-- ── pokemon.csv ──
CREATE TABLE IF NOT EXISTS pokemon (
    id BIGINT PRIMARY KEY,
    name TEXT,
    form TEXT,
    unique_name TEXT,
    ndex BIGINT,
    galar_dex BIGINT,
    ioa_dex BIGINT,
    ct_dex BIGINT,
    paldea_dex BIGINT,
    tm_dex BIGINT,
    type1_id BIGINT,
    type2_id BIGINT,
    hp BIGINT,
    atk BIGINT,
    def BIGINT,
    spa BIGINT,
    spd BIGINT,
    spe BIGINT,
    egg_group1_id BIGINT,
    egg_group2_id BIGINT,
    gr_id BIGINT,
    ability1_id BIGINT,
    ability2_id BIGINT,
    hidden_ability_id BIGINT,
    egg_cycles BIGINT
);

-- UPSERT template for pokemon:
-- INSERT INTO pokemon (id, name, form, unique_name, ndex, galar_dex, ioa_dex, ct_dex, paldea_dex, tm_dex, type1_id, type2_id, hp, atk, def, spa, spd, spe, egg_group1_id, egg_group2_id, gr_id, ability1_id, ability2_id, hidden_ability_id, egg_cycles) VALUES (%(id)s, %(name)s, %(form)s, %(unique_name)s, %(ndex)s, %(galar_dex)s, %(ioa_dex)s, %(ct_dex)s, %(paldea_dex)s, %(tm_dex)s, %(type1_id)s, %(type2_id)s, %(hp)s, %(atk)s, %(def)s, %(spa)s, %(spd)s, %(spe)s, %(egg_group1_id)s, %(egg_group2_id)s, %(gr_id)s, %(ability1_id)s, %(ability2_id)s, %(hidden_ability_id)s, %(egg_cycles)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, form = EXCLUDED.form, unique_name = EXCLUDED.unique_name, ndex = EXCLUDED.ndex, galar_dex = EXCLUDED.galar_dex, ioa_dex = EXCLUDED.ioa_dex, ct_dex = EXCLUDED.ct_dex, paldea_dex = EXCLUDED.paldea_dex, tm_dex = EXCLUDED.tm_dex, type1_id = EXCLUDED.type1_id, type2_id = EXCLUDED.type2_id, hp = EXCLUDED.hp, atk = EXCLUDED.atk, def = EXCLUDED.def, spa = EXCLUDED.spa, spd = EXCLUDED.spd, spe = EXCLUDED.spe, egg_group1_id = EXCLUDED.egg_group1_id, egg_group2_id = EXCLUDED.egg_group2_id, gr_id = EXCLUDED.gr_id, ability1_id = EXCLUDED.ability1_id, ability2_id = EXCLUDED.ability2_id, hidden_ability_id = EXCLUDED.hidden_ability_id, egg_cycles = EXCLUDED.egg_cycles;

-- ── types.csv ──
CREATE TABLE IF NOT EXISTS types (
    id BIGINT PRIMARY KEY,
    name TEXT
);

-- UPSERT template for types:
-- INSERT INTO types (id, name) VALUES (%(id)s, %(name)s)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name;
